list(import = function() {
       run("2017/easurvey", to = "data")
       df2017 <- df %>% filter(ea_id != "" & !is.na(ea_id))
       names(df2017) <- paste0("s17_", names(df2017))
       run("2015/easurvey", to = "data")
       df2015 <- df %>% filter(ea_id != "" & !is.na(ea_id))
       names(df2015) <- paste0("s15_", names(df2015))
       inner_join(df2015, df2017, by = c("s15_ea_id" = "s17_ea_id"))
     },
     analyze = list(
       list(write = "data/2017/2017-longitudinal-analysis-tables.txt"),
       # list(write = "stdout"), # <-- toggle this to print to the screen.
       list(
         "N"                          = function(df) dim(df)
         , "[check] population aging" = function(df) var_summary(df$s17_age - as.numeric(df$s15_age), verbose = TRUE)
         , "[check] gender"           = function(df) tab(df, s17_gender, s15_gender)
         , "[check] first heard EA"   = function(df) tab(df, s15_first_heard_EA, s17_first_heard_EA)
         , "summarize 2014 donations" = function(df) var_summary(df$s15_donate_2014_c, verbose = TRUE)
         , "summarize 2015 donations" = function(df) var_summary(df$s17_donate_2015_c, verbose = TRUE)
         , "summarize 2016 donations" = function(df) var_summary(df$s17_donate_2016_c, verbose = TRUE)
         , "increase don? 2014->2015" = function(df) tab(df, df$s17_donate_2015_c > df$s15_donate_2014_c)
         , "increase don? 2015->2016" = function(df) tab(df, df$s17_donate_2016_c > df$s17_donate_2015_c)
         , "increase don? 2014->2016" = function(df) tab(df, df$s17_donate_2016_c > df$s15_donate_2014_c)
         , "summarize 2014 income"    = function(df) var_summary(df$s15_income_2014_c, verbose = TRUE)
         , "summarize 2015 income"    = function(df) var_summary(df$s17_income_2015_individual_c, verbose = TRUE)
         , "summarize 2016 income"    = function(df) var_summary(df$s17_income_2016_individual_c, verbose = TRUE)
         , "keep EA career"           = function(df) tab(df, s15_ea_career, s17_ea_career, na.rm = TRUE)
         , "EA career change"         = function(df) tab(df, s15_career_path, s17_ea_career_type)
         , "member EA FB"             = function(df) tab(df, s15_member_ea_fb, s17_member_ea_fb)
         , "member EA Forum"          = function(df) tab(df, s15_member_ea_forum, s17_member_ea_forum)
         , "member GWWC"              = function(df) tab(df, s15_member_gwwc, s17_member_gwwc)
         , "donate 10%? [2014-2015]"  = function(df) tab(df, s15_p_donate_2014_c >= 0.1, s17_p_donate_2015 >= 0.1)
         , "donate 10%? [2015-2016]"  = function(df) tab(df, s17_p_donate_2015 >= 0.1, s17_p_donate_2016 >= 0.1)
         , "donate 10% [2014-2016]"   = function(df) table(df$s15_p_donate_2014_c >= 0.1, df$s17_p_donate_2015 >= 0.1, df$s17_p_donate_2016 >= 0.1)
         , "donate 10% [2014-2016] II" = function(df) table((df$s15_p_donate_2014_c >= 0.1) + (df$s17_p_donate_2015 >= 0.1) + (df$s17_p_donate_2016 >= 0.1))
         , "donate? [2014-2016]"      = function(df) table(df$s15_donate_2014_c > 0, df$s17_donate_2015_c > 0, df$s17_donate_2016_c > 0)
         , "donate? [2014-2016] II"   = function(df) table((df$s15_donate_2014_c >= 0) + (df$s17_donate_2015_c > 0) + (df$s17_donate_2016_c > 0))
         , "member LW"                = function(df) tab(df, s15_member_lw, s17_member_lw)
         , "member local group"       = function(df) tab(df, s15_member_local_group, s17_member_local_group)
         , "veg"                      = function(df) tab(df, s15_veg, s17_veg)
         , "cause import AR"          = function(df) tab(df, s15_cause_import_animal_welfare, s17_cause_import_animal_welfare)
         , "cause import prioritize"  = function(df) tab(df, s15_cause_import_cause_prioritization, s17_cause_import_cause_prioritization)
         , "cause environment"        = function(df) tab(df, s15_cause_import_environmentalism, s17_cause_import_environmentalism)
         , "cause AI"                 = function(df) tab(df, s15_cause_import_ai, s17_cause_import_ai)
         , "cause non-AI far future"  = function(df) tab(df, s15_cause_import_non_ai_far_future, s17_cause_import_non_ai_far_future)
         , "cause poverty"            = function(df) tab(df, s15_cause_import_poverty, s17_cause_import_poverty)
         , "cause rationality"        = function(df) tab(df, s15_cause_import_rationality, s17_cause_import_rationality)
         , "cause politics"           = function(df) tab(df, s15_cause_import_politics, s17_cause_import_politics)
         , "cause meta"               = function(df) tab(df, s15_cause_import_meta, s17_cause_import_meta)
         , "cause AR II"              = function(df) tab(df, s15_cause_import_animal_welfare %in% c("This cause is the top priority", "This cause is near the top priority"), s17_cause_import_animal_welfare_b, na.rm = TRUE, percent = TRUE, byrow = NULL)
         , "cause import prioriti II" = function(df) tab(df, s15_cause_import_cause_prioritization %in% c("This cause is the top priority", "This cause is near the top priority"), s17_cause_import_cause_prioritization_b, na.rm = TRUE, percent = TRUE, byrow = NULL)
         , "cause import environm II" = function(df) tab(df, s15_cause_import_environmentalism %in% c("This cause is the top priority", "This cause is near the top priority"), s17_cause_import_environmentalism_b, na.rm = TRUE, percent = TRUE, byrow = NULL)
         , "cause AI II"              = function(df) tab(df, s15_cause_import_ai %in% c("This cause is the top priority", "This cause is near the top priority"), s17_cause_import_ai_b, percent = TRUE, na.rm = TRUE, byrow = NULL)
         , "cause AI III"             = function(df) tab(df, s15_cause_import_ai %in% "This cause is the top priority", s17_cause_import_ai %in% "This cause should be the top priority", percent = TRUE, na.rm = TRUE, byrow = NULL)
         , "cause non-AI II"          = function(df) tab(df, s15_cause_import_non_ai_far_future %in% c("This cause is the top priority", "This cause is near the top priority"), s17_cause_import_non_ai_far_future_b, na.rm = TRUE, percent = TRUE, byrow = NULL)
         , "cause poverty II"         = function(df) tab(df, s15_cause_import_poverty %in% c("This cause is the top priority", "This cause is near the top priority"), s17_cause_import_poverty_b, percent = TRUE, na.rm = TRUE, byrow = NULL)
         , "cause poverty III"        = function(df) tab(df, s15_cause_import_poverty %in% "This cause is the top priority", s17_cause_import_poverty %in% "This cause should be the top priority", percent = TRUE, na.rm = TRUE, byrow = NULL)
         , "cause rationality II"     = function(df) tab(df, s15_cause_import_rationality %in% c("This cause is the top priority", "This cause is near the top priority"), s17_cause_import_rationality_b, percent = TRUE, na.rm = TRUE, byrow = NULL)
         , "cause politics II"        = function(df) tab(df, s15_cause_import_politics %in% c("This cause is the top priority", "This cause is near the top priority"), s17_cause_import_politics_b, percent = TRUE, na.rm = TRUE, byrow = NULL)
         , "cause meta II"            = function(df) tab(df, s15_cause_import_meta %in% c("This cause is the top priority", "This cause is near the top priority"), s17_cause_import_meta_b, percent = TRUE, byrow = NULL)
         , "politics"                 = function(df) tab(df, s15_politics, s17_politics)
     )))
