list(
	list(id = 1, value = "Respondent ID", name = "id"),
	list(id = 2, value = "Collector ID", name = "referrer_id"),
  list(id = 10, value = "Are you a group leader or a member?Only one organiser per group needs to fill out the survey. If your group has more than one organiser, please select one \"group leader\" to fill the survey out on behalf of the organisers. All other organisers can fill the survey out as members.", name = "is_member"),
  list(id = 16, value = "Group Name", name = "group_name"),
  list(id = 85, value = "Group Name", name = "group_name2"),
  list(id = 17, value = "If you don't have an official group email address, would you like one?", name = "want_group_email"),
  list(id = 18, value = "Group Email Address (If you currently have one)", name = "has_group_email"),
  list(id = 21, value = "Group Website (If you currently have one)", name = "has_website"),
  list(id = 22, value = "Group Meetup.com page (If you currently have one)", name = "has_meetup"),
  list(id = 23, value = "What type is your group?", name = "group_type"),
  list(id = 24, value = "How many group members do you have?", name = "num_group_members"),
  list(id = 31, value = "When did your group first form? Specify by season and year (e.g. Spring 2017).", name = "when_group"),
  list(id = 32, value = "In the last year, roughly how many people have attended at least one of your events, who weren’t familiar (or were barely familiar) with effective altruism beforehand?", name = "num_new_eas"),
  list(id = 33, value = "How likely do you think it is that your group will continue to function after the current organisers leave?", name = "survive_without_current_organizers"),
  list(id = 34, value = "For each of the following kind of events, please specify how many your group has hosted in the last year, and the average attendance. Please enter your answers using the following convention: number of events, average attendees (e.g. 2, 13).", name = "num_events_speaker_events"),
  list(id = 35, value = NA, name = "num_events_discussion_groups"),
  list(id = 36, value = NA, name = "num_events_socials"),
  list(id = 37, value = NA, name = "num_events_coworking"),
  list(id = 38, value = NA, name = "num_events_committee_meetings"),
  list(id = 39, value = NA, name = "num_events_fundraisers"),
  list(id = 40, value = NA, name = "num_events_research_projects"),
  list(id = 41, value = NA, name = "num_events_career_workshops"),
  list(id = 42, value = NA, name = "num_events_eagx"),
  list(id = 43, value = NA, name = "num_events_other"),
  list(id = 44, value = "What outside help has been the most useful to the operation of your group?", name = "outside_help_gbs"),
  list(id = 45, value = NA, name = "outside_help_eaf"),
  list(id = 46, value = NA, name = "outside_help_ea_netherlands"),
  list(id = 47, value = NA, name = "outside_help_tlycs"),
  list(id = 48, value = NA, name = "outside_help_lean"),
  list(id = 49, value = NA, name = "outside_help_oftw"),
  list(id = 50, value = NA, name = "outside_help_80K"),
  list(id = 51, value = NA, name = "outside_help_gwwc"),
  list(id = 52, value = NA, name = "outside_help_CEA"),
  list(id = 53, value = NA, name = "outside_help_other"),
  list(id = 54, value = "What do you see as the main purpose of your group?", name = "group_purpose"),
  list(id = 56, value = "If your group uses Meetup.com, please give an estimation of the % more attendees you have attracted as a result of using the platform in addition to - or instead of - alternatives?", name = "pct_members_from_meetupcom"),
  list(id = 57, value = "Do you have a Facebook page or group?", name = "has_fb"),
  list(id = 58, value = "If you have both, which of these has been most successful in attracting members or expressions of interest?", name = "fb_page_better_than_fb_group"),
  list(id = 59, value = "If you only have a page or only a group, what are your reasons for preferring one over the other?", name = "why_fb_page_or_group"),
  list(id = 60, value = "If your group uses a website, do you believe that it makes a non-trivial difference in the effectiveness of your group's outreach efforts?", name = "value_website"),
  list(id = 61, value = "In your opinion, how useful is it to host video calls about group management topics?", name = "value_group_calls"),
  list(id = 62, value = "In your opinion, how useful is the EA Groups Slack Team?", name = "value_group_slack"),
  list(id = 63, value = "In your opinion, how useful is the Facebook community of group organisers?", name = "value_group_fb"),
  list(id = 64, value = "In your opinion, how useful is it to receive practical support and new ideas for group activities?", name = "value_support"),
  list(id = 65, value = "In your opinion, how useful is the EA Organiser's Mentoring Programme?", name = "value_mentor_program"),
  list(id = 66, value = "In your opinion, how useful is the Local Group Newsletter?", name = "value_group_newsletter"),
  list(id = 67, value = "In your opinion, how useful are written guides (with a focus on practical and strategic aspects of organising groups)?", name = "value_written_guides"),
  list(id = 68, value = "In your opinion, how useful is personal feedback and support via social media, email and video call?", name = "value_personal_support"),
  list(id = 69, value = "In your opinion, how useful is technical support (for instance, subscriptions for online services, free websites, group email addresses)?", name = "value_tech"),
  list(id = 70, value = "Are there any other resources or services you would find helpful?", name = "comment_what_else_would_help"),
  list(id = 71, value = "How many of your current members do you expect to choose careers based on EA recommendations or thinking?", name = "num_career_changes"),
  list(id = 72, value = "How much money, if any, has been raised through collective fundraising efforts by your group (such as the Living on Less fundraiser)?", name = "amount_fundraising"),
  list(id = 73, value = "If you can, please estimate the net counterfactual sum of private donations from your members. That is the combined total of donations made by individual donors in your group, who otherwise would not have donated.", name = "amount_donations"),
  list(id = 74, value = "How many members have become actively committed to EA as a result of being in your group? Examples of active commitment include lifestyle changes, direct action or donating money to effective causes.", name = "num_ea_commitments"),
  list(id = 75, value = "How many members have taken the GWWC Pledge?", name = "num_pledges"),
  list(id = 76, value = "How many of these would not have taken the pledge without encountering your group? A rough estimate is acceptable.", name = "num_noncounterfactual_pledges"),
  list(id = 77, value = "Please name any current or past group members who have gone on to become active in the wider EA community. This would include going on to work at an EA organization, starting an EA project, become a thought leader in the movement, earning to give, and/or representing EA in other public ways.", name = "has_active_eas"),
  list(id = 78, value = "What is the narrative history of your group's formation?", name = "comment_group_history"),
  list(id = 79, value = "How did you find your core organizers and members, particularly the early ones?", name = "comment_group_organizer_history"),
  list(id = 80, value = "Are there any specific opportunities that had a large impact on your group's development? For example, applying for charity status, hosting an EAX conference, hosting a speaker event, running a fundraiser, etc.", name = "comment_group_dev_opportunity"),
  list(id = 81, value = "What advice would you give your group a year ago?", name = "comment_group_advice"),
  list(id = 82, value = "What are the main challenges your group faces?", name = "comment_group_challenges"),
  list(id = 86, value = "Are you... (select all that apply)", name = "is_regular_member"),
  list(id = 87, value = NA, name = "is_occasional_member"),
  list(id = 88, value = NA, name = "is_organizer"),
  list(id = 89, value = NA, name = "is_former_organizer"),
  list(id = 91, value = "Are you:", name = "student_status"),
  list(id = 94, value = "Which of the following are true of you? Select all that apply.", name = "has_volunteered_at_ea_org"),
  list(id = 95, value = NA, name = "has_interned_at_ea_org"),
  list(id = 96, value = NA, name = "has_written_ea"),
  list(id = 97, value = NA, name = "has_attended_eag"),
  list(id = 98, value = NA, name = "has_attended_eagx"),
  list(id = 99, value = NA, name = "is_ea_online"),
  list(id = 100, value = NA, name = "is_ea_forum_reader"),
  list(id = 101, value = "Did you consider yourself an Effective Altruist (EA) before you attended a group meeting?", name = "prior_ea"),
  list(id = 102, value = "How many group events or meetings have you ever attended?", name = "num_attendance"),
  list(id = 108, value = "How much of a factor has being involved with your EA group been for engagement in EA?", name = "ea_group_important_for_ea"),
  list(id = 109, value = "If applicable, how much of a factor are or were EA principles in planning your career?", name = "ea_important_for_career"),
  list(id = 110, value = "Which problem area do you see as highest priority?", name = "top_cause"),
  list(id = 112, value = "Describe your current future plans for impact in three sentences", name = "comment_ea_career_plan"),
  list(id = 113, value = "How could the EA community help you achieve these plans?", name = "comment_how_ea_help_plans"),
  list(id = 121, value = "Has the way you’ve thought about the world and/or your behavior changed in any way since being involved with your local group? For example, changes in consumption habits, career plans or giving.", name = "ea_group_important_for_thoughts"),
  list(id = 122, value = "If there has been a difference, do you expect to have more social impact as a result of this change?", name = "changed_thoughts_more_impact"),
  list(id = 130, value = "Are there any other ways in which being part of a local group has helped you?", name = "comment_how_local_group_helps"),
  list(id = 131, value = "Are there any features about Effective Altruism that have been offputting to you?", name = "comment_how_ea_offputting"),
  list(id = 132, value = "How valuable do you find your group's activities?", name = "group_valuable"),
  list(id = 133, value = "In what way could the group provide more value to you?", name = "commment_how_make_group_more_valuable"),
  list(id = 134, value = "What are your strongest motivators for being part of a local group? Please rank.", name = "motivators_rank_interacting_with_eas"),
  list(id = 135, value = NA, name = "motivators_rank_having_responsibility"),
  list(id = 136, value = NA, name = "motivators_rank_enjoyable_activities"),
  list(id = 137, value = NA, name = "motivators_rank_interesting_content"),
  list(id = 138, value = "Are you a member of Giving What We Can?", name = "member_gwwc"))
