define("variable_names", function(variable_names) {
  list(
    #TODO: Longitudinal study
    import = list(file = "data/imsurvey2015-anonymized-renamed-currencied.csv"),
    data   = list(
      "Rename variables" = list(renamer, variable_names)
      , "Drop time vars" = list(function(df) { df[!grepl(".time", names(df), fixed = TRUE)] })
      , "Drop insincere" = list(select_rows, function(df) grepl("Yes", df$sincere, fixed = TRUE), whole = TRUE)
      , "Drop non-EA"    = list(select_rows, function(df) df$is_ea == "Yes", whole = TRUE)
      # TODO: Publish comments
      , "Drop comments"  = list(function(df) { df[!grepl("comment", names(df), fixed = TRUE)] })
      , "Have a plan"    = list(new_variable, function(plan_donate_how_much, already_stated_plan, donate_2014) {
        plan_donate_how_much != "" | already_stated_plan == "Yes" | !is.na(donate_2014)
      }, "have_donation_plan")
      , "Sold EA"        = list(new_variable, function(have_donation_plan, ea_career) {
        have_donation_plan | ea_career == "Yes"
      }, "sold_ea")
      , "% inc donate"   = list(new_variable, function(donate_2014_c, income_2014_c) {
        p <- donate_2014_c / income_2014_c
        p[is.infinite(p)] <- NA
        p
      }, "p_donate_2014_c")
    )

    , analyze = list(
      "num respondents"                 = function(df) num_respondents(df)
      , "first heard about EA"          = function(df) tab(df, first_heard_EA)
      , "EA year"                       = function(df) tab(df, which_year_EA)
      , "how heard x year"              = function(df) ctab(df, first_heard_EA, which_year_EA)
      , "how heard x year (freq)"       = function(df) tab(df, first_heard_EA, which_year_EA)
      , "involved_TLYCS"                = function(df) tab(df, involved_TLYCS)
      , "involved_local_EA"             = function(df) tab(df, involved_local_EA)
      , "involved_lesswrong"            = function(df) tab(df, involved_lesswrong)
      , "involved_givewell"             = function(df) tab(df, involved_givewell)
      , "involved_online_ea"            = function(df) tab(df, involved_online_ea)
      , "involved_personal_contact"     = function(df) tab(df, involved_personal_contact)
      , "involved_80K"                  = function(df) tab(df, involved_80K)
      , "involved_GWWC"                 = function(df) tab(df, involved_GWWC)
      , "member_ea_fb"                  = function(df) tab(df, member_ea_fb)
      , "member_ea_forum"               = function(df) tab(df, member_ea_forum)
      , "member_gwwc"                   = function(df) tab(df, member_gwwc)
      , "member_lw"                     = function(df) tab(df, member_lw)
      , "member_tlycs"                  = function(df) tab(df, member_tlycs)
      , "member_local_group"            = function(df) tab(df, member_local_group)
      , "gender"                        = function(df) tab(df, gender)
      , "age"                           = function(df) tab(df, age)
      , "religion"                      = function(df) tab(df, religion)
      , "student"                       = function(df) tab(df, student)
      , "country"                       = function(df) tab(df, country)
      , "city"                          = function(df) tab(df, city)
      , "cause_import_animal_welfare"   = function(df) tab(df, cause_import_animal_welfare)
      , "cause_import_cause_prioritization"   = function(df) tab(df, cause_import_cause_prioritization)
      , "cause_import_environmentalism"       = function(df) tab(df, cause_import_environmentalism)
      , "cause_import_ai"                     = function(df) tab(df, cause_import_ai)
      , "cause_import_non_ai_far_future"      = function(df) tab(df, cause_import_non_ai_far_future)
      , "cause_import_poverty"          = function(df) tab(df, cause_import_poverty)
      , "cause_import_rationality"      = function(df) tab(df, cause_import_rationality)
      , "cause_import_politics"         = function(df) tab(df, cause_import_politics)
      , "cause_import_meta"             = function(df) tab(df, cause_import_meta)
      , "first heard through local grp" = function(df) tab(df, first_heard_EA == "Local EA group")
      , "first heard local x GWWC mem"  = function(df) ctab(df, member_gwwc, first_heard_EA == "Local EA group")
      , "first heard local x donate"    = function(df) ctab(df, donate_2014_c, first_heard_EA == "Local EA group")
      , "would attend"                  = function(df) tab(df, would_attend_local_group)
      , "involved_local_EA x GWWC invo" = function(df) ctab(df, involved_local_EA, involved_GWWC)
      , "involved_local_EA x GWWC mem"  = function(df) ctab(df, involved_local_EA, member_gwwc)
      , "involved_GWWC x GWWC mem"      = function(df) ctab(df, involved_GWWC, member_gwwc)
      , "involved_local_EA x donate"    = function(df) ctab(df, donate_2014_c, involved_local_EA)
      , "member_local x GWWC"           = function(df) ctab(df, member_local_group, member_gwwc)
      , "involved_local_EA x local mem" = function(df) ctab(df, involved_local_EA, member_local_group)
      , "member_local x year"           = function(df) ctab(df, member_local_group, which_year_EA)
      , "member_local x donate"         = function(df) ctab(df, donate_2014_c, member_local_group)
      , "GWWC x donate"                 = function(df) ctab(df, donate_2014_c, member_gwwc)
      , "member_local x donate %"       = function(df) ctab(df, p_donate_2014_c, member_local_group)
      , "GWWC x donate %"               = function(df) ctab(df, p_donate_2014_c, member_gwwc)
      , "member_local x student"        = function(df) ctab(df, member_local_group, student)
      , "member_local x welcoming"      = function(df) ctab(df, member_local_group, ea_welcoming)
      , "member_gwwc x welcoming"       = function(df) ctab(df, member_gwwc, ea_welcoming)
      , "member_local x fundraiser"     = function(df) ctab(df, member_local_group, action_fundraiser)
      , "member_gwwc x fundraiser"      = function(df) ctab(df, member_gwwc, action_fundraiser)
      , "member_local x legacy"         = function(df) ctab(df, member_local_group, action_legacy)
      , "member_gwwc x legacy"          = function(df) ctab(df, member_gwwc, action_legacy)
      , "member_local x telling_friends"   = function(df) ctab(df, member_local_group, action_telling_friends)
      , "member_gwwc x telling_friends"    = function(df) ctab(df, member_gwwc, action_telling_friends)
      , "member_local x ea_newsletter"     = function(df) ctab(df, member_local_group, action_ea_newsletter)
      , "member_gwwc x ea_newsletter"      = function(df) ctab(df, member_gwwc, action_ea_newsletter)
      , "donate_80K"                    = function(df) tab(df, donate_80K)
      , "donate_amf"                    = function(df) tab(df, donate_amf)
      , "donate_ace"                    = function(df) tab(df, donate_ace)
      , "donate_cea"                    = function(df) tab(df, donate_cea)
      , "donate_cfar"                   = function(df) tab(df, donate_cfar)
      , "donate_dtw"                    = function(df) tab(df, donate_dtw)
      , "donate_gd"                     = function(df) tab(df, donate_gd)
      , "donate_gw"                     = function(df) tab(df, donate_gw)
      , "donate_gwwc"                   = function(df) tab(df, donate_gwwc)
      , "donate_thl"                    = function(df) tab(df, donate_thl)
      , "donate_leverage"               = function(df) tab(df, donate_leverage)
      , "donate_miri"                   = function(df) tab(df, donate_miri)
      , "donate_phc"                    = function(df) tab(df, donate_phc)
      , "donate_sci"                    = function(df) tab(df, donate_sci)
      , "donate_vo"                     = function(df) tab(df, donate_vo)
      , "MIRI donations by year"        = function(df) ctab(df %>% filter(donate_2014_c > 0), donate_miri, which_year_EA, na.rm = TRUE)
      , "AMF donations by year"         = function(df) ctab(df %>% filter(donate_2014_c > 0), donate_amf, which_year_EA, na.rm = TRUE)
      , "AMF donations by first heard"  = function(df) ctab(df %>% filter(donate_2014_c > 0), donate_amf, first_heard_EA, na.rm = TRUE)
      , "AMF donations by first heard 2"    = function(df) tab(df %>% filter(donate_2014_c > 0), donate_amf, first_heard_EA, na.rm = TRUE, freq = TRUE, percent = TRUE)
      , "MIRI donations by first heard"     = function(df) ctab(df %>% filter(donate_2014_c > 0), donate_miri, first_heard_EA, na.rm = TRUE)
      , "MIRI donations by first heard 2"   = function(df) tab(df %>% filter(donate_2014_c > 0), donate_miri, first_heard_EA, na.rm = TRUE, freq = TRUE, percent = TRUE)
      , "summarize donations"           = function(df) var_summary(df$donate_2014_c)
      , "number of >0 donations"        = function(df) sum(df$donate_2014_c > 0, na.rm = TRUE)
      , "donation quantile 1"           = function(df) quantile(df$donate_2014_c, probs = seq(0.1, 1, len = 10), na.rm = TRUE)
      , "donation quantile 2"           = function(df) quantile(df$donate_2014_c, probs = seq(0.91, 1, len = 10), na.rm = TRUE)
      , "summarize % donations"         = function(df) var_summary(df$p_donate_2014_c)
      , "% donation quantile 1"         = function(df) quantile(df[df$income_2014_c > 10000, "p_donate_2014_c"], probs = seq(0.1, 1, len = 10), na.rm = TRUE)
      , "% donation quantile 2"         = function(df) quantile(df[df$income_2014_c > 10000, "p_donate_2014_c"], probs = seq(0.91, 1, len = 10), na.rm = TRUE)
      , "# people donating over 10%"    = function(df) sum(df[df$income_2014_c > 10000, "p_donate_2014_c"] > 0.1, na.rm = TRUE)
      , "donating over 10% x GWWC"      = function(df) ctab(df, p_donate_2014_c > 0.1, member_gwwc)
      , "diet"                          = function(df) tab(df, veg)
      , "diet x cause_import_animal_welfare"  = function(df) ctab(df, veg, cause_import_animal_welfare, na.rm = TRUE)
    )
  )
})
