define("transform_lookups", "transform_functions", function(transform_lookup, transform_functions) {
  list(
    import = list(file = "data/imsurvey2014-anonymized.csv")
    , data = list(
      "Rename variables sensibly"       = list(renamer, transform_lookup$renames)
      ,"Make age numeric"               = list(column_transformation(as.numeric), 'age')
      ,"Unlist ids"                     = list(replace_variable, function(id) unlist(id))
      ,"Drop NA ids"                    = list(select_rows, function(dataframe) { !is.na(dataframe$id) }, whole = TRUE) 
      ,"Clean values in meta-ethics"    = list(value_replacer, 'metaethics', list(list('Consequentialist/utilitarian', 'consequentialist'), list('Deontology', 'deontology'), list('Virtue ethics', 'virtue'), list('Other', 'other'), list('No opinion, or not familiar with these terms', 'other')))
      ,"Make reducitarian variable"     = list(new_variable, function(diet) ifelse(diet == 'Meat-eating', FALSE, TRUE), 'reducitarian')
      ,"Make veg binary variable"       = list(new_variable, function(diet) ifelse(diet == 'Vegetarian', TRUE, ifelse(diet == 'Vegan', TRUE, FALSE)), 'veg')
      ,"Clean up atheist response"      = list(value_replacer, 'religion', list(list('Atheist, agnostic or non-religious', 'atheist')))
      ,"Clean up group responses"       = list(value_replacer, 'group', transform_lookup$clean_group)
      ,"Impute TLYCS factors"           = list(impute, surveytools2::swap_multiple_ids, 'involved_TLYCS', c(13, 31, 79, 110, 146, 367, 374, 383, 534, 577), 'Yes')
      ,"Impute online factors"          = list(impute, surveytools2::swap_multiple_ids, 'factors_online', c(361, 374, 606), 'Yes')
      ,"Consolidate sublovation"        = list(value_replacer, transform_lookup$clean_city)
      ,'Clean up career responses'      = list(value_replacer, list(list('Direct charity/non-profit work', 'Direct'), list('Earning to Give', 'ETG'), list('None of these', 'None'), list('Research', 'Research'), list('Other', 'None')))
      ,'Number of charities donated'    = list(charity_count, transform_lookup$charity_vars)
      ,'Impute career responses'        = list(swap_by_ids, 'career', transform_lookup$career_transform)
      ,'Impute donate responses'        = list(swap_by_ids, 'donate_2013_c', transform_lookup$donate_transform)
      ,'Impute income responses'        = list(swap_by_ids, 'income_2013_c', transform_lookup$income_transform)
      ,'Make p_inc_donate'              = list(new_variable, transform_functions$make_p_inc_donate, 'p_donate_2013_c')
      ,"Make income numeric"            = list(column_transformation(as.numeric), 'income_2013_c')
      ,"Make donations numeric"         = list(column_transformation(as.numeric), 'donate_2013_c')
      ,"Make p_inc_donate numeric"      = list(column_transformation(as.numeric), 'p_donate_2013_c')
      ,"Earning to give?"               = list(new_variable, function(income_2013_c, p_donate_2013_c) { ifelse(income_2013_c >= 60000 & p_donate_2013_c >= 0.1, TRUE, FALSE) }, 'is.ETG')
      ,"Trim referrer_url"                  = list(replace_variable, function(referrer_url) { r <- referrer_url; r[grepl('\\?', r)] <- sapply(strsplit(r[grepl('\\?', r)], '\\?'), '[', 2); r[nchar(r) > 12] <- ""; r[substring(r, 1, 1) == 't' & !is.na(r)] <- "t"; r })
      ,'Clean referrer_url'                 = list(value_replacer, 'referrer_url', transform_lookup$referrer)
      ,"Trim referrer2"                 = list(replace_variable, function(referrer2) { referrer2[nchar(referrer2) < 5] <- ""; referrer2 })
      ,'Clean referrer2'                = list(value_replacer, 'referrer', transform_lookup$referrer2)
      ,'Impute ACE as a referrer'       = list(evaldf, quote({ dataframe[grepl('A', dataframe$id), 'referrer_url'] <- 'ACE'; dataframe[grepl('A', dataframe$id), 'referrer2'] <- 'ACE' }))
      ,'In random FB sample?'           = list(new_variable, function(id) id %in% transform_lookup$random_sample_ids, 'in_random_fb_sample')
    ),
    export = list(R = list('imdata', .type = 'data'))
  )
})
