Ramd::define("groups", function(groups) {
  list(import = function() { run("2017/easurvey", to = "data"); df },
       data = list(
         "First heard local" = function(df) { df$first_local <- df$first_heard_EA == "Local EA group"; df }
         , "EA NPS"          = function(df) {
           df <- swap_by_value(df, "ea_nps", list("10 (Completely likely)" = "10", "0 (Not at all likely)" = "0"))
           df$ea_nps_raw <- as.numeric(df$ea_nps)
           df$ea_nps <- ((df$ea_nps_raw >= 9) - (df$ea_nps_raw <= 6)) * 100
           df
         }
         , "Groups"          = function(df) {
           groupmap <- groups$cities_to_groups
           df$group1 <- swap_by_value(df, "city", lapply(groupmap, `[`, 1))$city
           df$group2 <- swap_by_value(df, "city", lapply(groupmap, `[`, 2))$city
           df$group3 <- swap_by_value(df, "city", lapply(groupmap, `[`, 3))$city
           df$group4 <- swap_by_value(df, "city", lapply(groupmap, `[`, 4))$city
           df$group5 <- swap_by_value(df, "city", lapply(groupmap, `[`, 5))$city
           df$group1 <- ifelse(df$member_local_group == "Yes", df$group1, NA)
           df$group2 <- ifelse(df$member_local_group == "Yes", df$group2, NA)
           df$group3 <- ifelse(df$member_local_group == "Yes", df$group3, NA)
           df$group4 <- ifelse(df$member_local_group == "Yes", df$group4, NA)
           df$group5 <- ifelse(df$member_local_group == "Yes", df$group5, NA)
           df$group1 <- ifelse(df$group1 == "", "Unknown Group", df$group1)
           df$group2 <- ifelse(df$group2 == "", NA, df$group2)
           df$group3 <- ifelse(df$group3 == "", NA, df$group3)
           df$group4 <- ifelse(df$group4 == "", NA, df$group4)
           df$group5 <- ifelse(df$group5 == "", NA, df$group5)
           is_lean <- lapply(groupmap, function(group) any(group %in% groups$lean_groups))
           df$is_lean <- swap_by_value(df, "city", is_lean)$city
           df$is_lean <- ifelse(df$member_local_group == "Yes", df$is_lean, NA)
           df$is_lean <- ifelse(df$group1 == "Unknown Group", NA, df$is_lean)
           df$is_lean <- as.logical(df$is_lean)
           df
         }
       ),
       analyze = list(
         list(write = "data/2017/2017-lean-analysis-tables.txt"),
         # list(write = "stdout"), # <-- toggle this to print to the screen.
         list(
            "first heard"                   = function(df) tab(df, first_heard_EA, percent = TRUE, byrow = FALSE, na.rm = TRUE)
          , "first local"                   = function(df) tab(df, first_local, percent = TRUE, byrow = FALSE, na.rm = TRUE)
          , "involved_TLYCS"                = function(df) tab(df, involved_TLYCS, percent = TRUE, byrow = FALSE, na.rm = TRUE)
          , "involved_local_EA"             = function(df) tab(df, involved_local_EA, percent = TRUE, byrow = FALSE, na.rm = TRUE)
          , "involved_lesswrong"            = function(df) tab(df, involved_lesswrong, percent = TRUE, byrow = FALSE, na.rm = TRUE)
          , "involved_givewell"             = function(df) tab(df, involved_givewell, percent = TRUE, byrow = FALSE, na.rm = TRUE)
          , "involved_online_ea"            = function(df) tab(df, involved_online_ea, percent = TRUE, byrow = FALSE, na.rm = TRUE)
          , "involved_personal_contact"     = function(df) tab(df, involved_personal_contact, percent = TRUE, byrow = FALSE, na.rm = TRUE)
          , "involved_80K"                  = function(df) tab(df, involved_80K, percent = TRUE, byrow = FALSE, na.rm = TRUE)
          , "involved_GWWC"                 = function(df) tab(df, involved_GWWC, percent = TRUE, byrow = FALSE, na.rm = TRUE)
          , "involved EA Global"            = function(df) tab(df, involved_ea_global, percent = TRUE, byrow = FALSE, na.rm = TRUE)
          , "involved Book or Blog"         = function(df) tab(df, involved_book_blog, percent = TRUE, byrow = FALSE, na.rm = TRUE)
          , "involved Swiss"                = function(df) tab(df, involved_swiss, percent = TRUE, byrow = FALSE, na.rm = TRUE)
          , "member_ea_fb"                  = function(df) tab(df, member_ea_fb, percent = TRUE, byrow = FALSE, na.rm = TRUE)
          , "member_ea_forum"               = function(df) tab(df, member_ea_forum, percent = TRUE, byrow = FALSE, na.rm = TRUE)
          , "member_gwwc"                   = function(df) tab(df, member_gwwc, percent = TRUE, byrow = FALSE, na.rm = TRUE)
          , "member_lw"                     = function(df) tab(df, member_lw, percent = TRUE, byrow = FALSE, na.rm = TRUE)
          , "ea social"                     = function(df) tab(df, ea_social, percent = TRUE, byrow = FALSE, na.rm = TRUE)
          , "would attend"                  = function(df) tab(df, would_attend_local_group, percent = TRUE, byrow = FALSE, na.rm = TRUE)
          , "ea_donate"                     = function(df) tab(df, ea_donate, percent = TRUE, byrow = FALSE, na.rm = TRUE)
          , "member local x ea social"      = function(df) ctab(df, ea_social, member_local_group, na.rm = TRUE)
          , "would attend x ea social"      = function(df) ctab(df, would_attend_local_group, ea_social, na.rm = TRUE)
          , "ea_donate x member local"      = function(df) ctab(df, ea_donate, member_local_group, na.rm = TRUE)
          , "ea_donate x member EA Forum"   = function(df) ctab(df, ea_donate, member_ea_forum, na.rm = TRUE)
          , "ea_donate x member EA FB"      = function(df) ctab(df, ea_donate, member_ea_fb, na.rm = TRUE)
          , "ea_donate x involved local"    = function(df) ctab(df, ea_donate, involved_local_EA, na.rm = TRUE)
          , "ea_donate x involved GWWC"     = function(df) ctab(df, ea_donate, involved_GWWC, na.rm = TRUE)
          , "ea_donate x involved 80K"      = function(df) ctab(df, ea_donate, involved_80K, na.rm = TRUE)
          , "ea_donate x involved GW"       = function(df) ctab(df, ea_donate, involved_givewell, na.rm = TRUE)
          , "ea_donate x involved online"   = function(df) ctab(df, ea_donate, involved_online_ea, na.rm = TRUE)
          , "ea_donate x involved book"     = function(df) ctab(df, ea_donate, involved_book_blog, na.rm = TRUE)
          , "ea_donate x first local"       = function(df) ctab(df, ea_donate, first_local, na.rm = TRUE)
          , "ea_donate x would attend"      = function(df) ctab(df, ea_donate, would_attend_local_group, na.rm = TRUE)
          , "ea_donate x ea social"         = function(df) ctab(df, ea_donate, ea_social, na.rm = TRUE)
          , "ea_volunteer"                  = function(df) tab(df, ea_volunteer, percent = TRUE, byrow = FALSE, na.rm = TRUE)
          , "ea_volunteer x member local"   = function(df) ctab(df, ea_volunteer, member_local_group, na.rm = TRUE)
          , "ea_volunteer x member EA For"  = function(df) ctab(df, ea_volunteer, member_ea_forum, na.rm = TRUE)
          , "ea_volunteer x member EA FB"   = function(df) ctab(df, ea_volunteer, member_ea_fb, na.rm = TRUE)
          , "ea_volunteer x member GWWC"    = function(df) ctab(df, ea_volunteer, member_gwwc, na.rm = TRUE)
          , "ea_volunteer x involved local" = function(df) ctab(df, ea_volunteer, involved_local_EA, na.rm = TRUE)
          , "ea_volunteer x involved GWWC"  = function(df) ctab(df, ea_volunteer, involved_GWWC, na.rm = TRUE)
          , "ea_volunteer x involved 80K"   = function(df) ctab(df, ea_volunteer, involved_80K, na.rm = TRUE)
          , "ea_volunteer x involved GW"    = function(df) ctab(df, ea_volunteer, involved_givewell, na.rm = TRUE)
          , "ea_volunteer x involved online" = function(df) ctab(df, ea_volunteer, involved_online_ea, na.rm = TRUE)
          , "ea_volunteer x involved book"  = function(df) ctab(df, ea_volunteer, involved_book_blog, na.rm = TRUE)
          , "ea_volunteer x first local"    = function(df) ctab(df, ea_volunteer, first_local, na.rm = TRUE)
          , "ea_volunteer x would attend"   = function(df) ctab(df, ea_volunteer, would_attend_local_group, na.rm = TRUE)
          , "ea_volunteer x ea social"      = function(df) ctab(df, ea_volunteer, ea_social, na.rm = TRUE)
          , "ea_career"                     = function(df) tab(df, ea_career, percent = TRUE, byrow = FALSE, na.rm = TRUE)
          , "ea_career x member local"      = function(df) ctab(df, ea_career, member_local_group, na.rm = TRUE)
          , "ea_career x involved local"    = function(df) ctab(df, ea_career, involved_local_EA, na.rm = TRUE)
          , "ea_career x first local"       = function(df) ctab(df, ea_career, first_local, na.rm = TRUE)
          , "ea_career x would attend"      = function(df) ctab(df, ea_career, would_attend_local_group, na.rm = TRUE)
          , "ea_volunteer_hours"            = function(df) tab(df, ea_volunteer_hours, percent = TRUE, byrow = FALSE, na.rm = TRUE)
          , "ea_career x member local"      = function(df) ctab(df, ea_career, member_local_group, na.rm = TRUE)
          , "ea_career x involved local"    = function(df) ctab(df, ea_career, involved_local_EA, na.rm = TRUE)
          , "ea_career x first local"       = function(df) ctab(df, ea_career, first_local, na.rm = TRUE)
          , "ea_career x would attend"      = function(df) ctab(df, ea_career, would_attend_local_group, na.rm = TRUE)
          , "ea_career x ea social"         = function(df) ctab(df, ea_career, ea_social, na.rm = TRUE)
          , "ea_volunteer_hours"            = function(df) tab(df, ea_volunteer_hours, percent = TRUE, byrow = FALSE, na.rm = TRUE)
          , "vol hrs x member local"        = function(df) ctab(df, ea_volunteer_hours, member_local_group, na.rm = TRUE)
          , "vol hrs x involved local"      = function(df) ctab(df, ea_volunteer_hours, involved_local_EA, na.rm = TRUE)
          , "vol hrs x first local"         = function(df) ctab(df, ea_volunteer_hours, first_local, na.rm = TRUE)
          , "vol hrs x would attend"        = function(df) ctab(df, ea_volunteer_hours, would_attend_local_group, na.rm = TRUE)
          , "vol hrs x ea social"           = function(df) ctab(df, ea_volunteer_hours, ea_social, na.rm = TRUE)
          , "ea_paid_hours"                 = function(df) tab(df, ea_paid_hours, percent = TRUE, byrow = FALSE, na.rm = TRUE)
          , "paid hrs x member local"       = function(df) ctab(df, ea_paid_hours, member_local_group, na.rm = TRUE)
          , "paid hrs x involved local"     = function(df) ctab(df, ea_paid_hours, involved_local_EA, na.rm = TRUE)
          , "paid hrs x first local"        = function(df) ctab(df, ea_paid_hours, first_local, na.rm = TRUE)
          , "paid hrs x would attend"       = function(df) ctab(df, ea_paid_hours, would_attend_local_group, na.rm = TRUE)
          , "paid hrs x ea social"          = function(df) ctab(df, ea_paid_hours, ea_social, na.rm = TRUE)
          , "Welcoming"                     = function(df) tab(df, ea_welcoming, percent = TRUE, byrow = FALSE, na.rm = TRUE)
          , "Welcoming x member local"      = function(df) ctab(df, ea_welcoming, member_local_group, na.rm = TRUE)
          , "Welcoming x member GWWC"       = function(df) ctab(df, ea_welcoming, member_gwwc, na.rm = TRUE)
          , "Welcoming x member EA Forum"   = function(df) ctab(df, ea_welcoming, member_ea_forum, na.rm = TRUE)
          , "Welcoming x member EA FB"      = function(df) ctab(df, ea_welcoming, member_ea_fb, na.rm = TRUE)
          , "Welcoming x involved local"    = function(df) ctab(df, ea_welcoming, involved_local_EA, na.rm = TRUE)
          , "Welcoming x involved GWWC"     = function(df) ctab(df, ea_welcoming, involved_GWWC, na.rm = TRUE)
          , "Welcoming x involved 80K"      = function(df) ctab(df, ea_welcoming, involved_80K, na.rm = TRUE)
          , "Welcoming x involved GW"       = function(df) ctab(df, ea_welcoming, involved_givewell, na.rm = TRUE)
          , "Welcoming x involved online"   = function(df) ctab(df, ea_welcoming, involved_online_ea, na.rm = TRUE)
          , "Welcoming x involved book"     = function(df) ctab(df, ea_welcoming, involved_book_blog, na.rm = TRUE)
          , "Welcoming x first local"       = function(df) ctab(df, ea_welcoming, first_local, na.rm = TRUE)
          , "Welcoming x would attend"      = function(df) ctab(df, ea_welcoming, would_attend_local_group, na.rm = TRUE)
          , "Welcoming x ea social"         = function(df) ctab(df, ea_welcoming, ea_social, na.rm = TRUE)
          , "EA NPS"                        = function(df) tab(df, ea_nps, percent = TRUE, byrow = FALSE, na.rm = TRUE)
          , "EA NPS Score"                  = function(df) sum(df$ea_nps, na.rm = TRUE) / length(na.rm(df$ea_nps))
          , "EA NPS x welcoming"            = function(df) tab(df, ea_nps, ea_welcoming, na.rm = TRUE)
          , "EA NPS x member local"         = function(df) ctab(df, ea_nps, member_local_group, na.rm = TRUE)
          , "EA NPS x member GWWC"          = function(df) ctab(df, ea_nps, member_gwwc, na.rm = TRUE)
          , "EA NPS x member EA Forum"      = function(df) ctab(df, ea_nps, member_ea_forum, na.rm = TRUE)
          , "EA NPS x member EA FB"         = function(df) ctab(df, ea_nps, member_ea_fb, na.rm = TRUE)
          , "EA NPS x involved local"       = function(df) ctab(df, ea_nps, involved_local_EA, na.rm = TRUE)
          , "EA NPS x involved GWWC"        = function(df) ctab(df, ea_nps, involved_GWWC, na.rm = TRUE)
          , "EA NPS x involved 80K"         = function(df) ctab(df, ea_nps, involved_80K, na.rm = TRUE)
          , "EA NPS x involved GW"          = function(df) ctab(df, ea_nps, involved_givewell, na.rm = TRUE)
          , "EA NPS x involved online"      = function(df) ctab(df, ea_nps, involved_online_ea, na.rm = TRUE)
          , "EA NPS x involved book"        = function(df) ctab(df, ea_nps, involved_book_blog, na.rm = TRUE)
          , "EA NPS x first local"          = function(df) ctab(df, ea_nps, first_local, na.rm = TRUE)
          , "EA NPS x would attend"         = function(df) ctab(df, ea_nps, would_attend_local_group, na.rm = TRUE)
          , "EA NPS x ea social"            = function(df) ctab(df, ea_nps, ea_social, na.rm = TRUE)
          , "student"                       = function(df) tab(df, student, percent = TRUE, byrow = FALSE, na.rm = TRUE)
          , "student x member local"        = function(df) ctab(df, student, member_local_group, na.rm = TRUE)
          , "which year EA"                 = function(df) tab(df, which_year_EA, percent = TRUE, byrow = FALSE, na.rm = TRUE)
          , "which year EA x member local"  = function(df) ctab(df, which_year_EA, member_local_group, na.rm = TRUE)
          , "GWWC member"                   = function(df) tab(df, member_gwwc, percent = TRUE, byrow = FALSE, na.rm = TRUE)
          , "GWWC member x student"         = function(df) ctab(df, member_gwwc, student, na.rm = TRUE)
          , "GWWC member x member local"    = function(df) ctab(df, member_gwwc, member_local_group, na.rm = TRUE)
          , "GWWC member x member EA Forum" = function(df) ctab(df, member_gwwc, member_ea_forum, na.rm = TRUE)
          , "GWWC member x member EA FB"    = function(df) ctab(df, member_gwwc, member_ea_fb, na.rm = TRUE)
          , "GWWC member x involved local"  = function(df) ctab(df, member_gwwc, involved_local_EA, na.rm = TRUE)
          , "GWWC member x involved 80K"    = function(df) ctab(df, member_gwwc, involved_80K, na.rm = TRUE)
          , "GWWC member x involved GW"     = function(df) ctab(df, member_gwwc, involved_givewell, na.rm = TRUE)
          , "GWWC member x involved online" = function(df) ctab(df, member_gwwc, involved_online_ea, na.rm = TRUE)
          , "GWWC member x involved book"   = function(df) ctab(df, member_gwwc, involved_book_blog, na.rm = TRUE)
          , "GWWC member x first local"     = function(df) ctab(df, member_gwwc, first_local, na.rm = TRUE)
          , "GWWC member x would attend"    = function(df) ctab(df, member_gwwc, would_attend_local_group, na.rm = TRUE)
          , "GWWC member x ea social"       = function(df) ctab(df, member_gwwc, ea_social, na.rm = TRUE)
          , "2016 Donate 1%?"                    = function(df) tab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), p_donate_2016 >= 0.01, percent = TRUE, byrow = FALSE, na.rm = TRUE)
          , "2016 Donate 1%? x member local"     = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), p_donate_2016 >= 0.01, member_local_group, na.rm = TRUE)
          , "2016 Donate 1%? x member EA Forum"  = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), p_donate_2016 >= 0.01, member_ea_forum, na.rm = TRUE)
          , "2016 Donate 1%? x member EA FB"     = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), p_donate_2016 >= 0.01, member_ea_fb, na.rm = TRUE)
          , "2016 Donate 1%? x involved local"   = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), p_donate_2016 >= 0.01, involved_local_EA, na.rm = TRUE)
          , "2016 Donate 1%? x involved 80K"     = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), p_donate_2016 >= 0.01, involved_80K, na.rm = TRUE)
          , "2016 Donate 1%? x involved GW"      = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), p_donate_2016 >= 0.01, involved_givewell, na.rm = TRUE)
          , "2016 Donate 1%? x involved online"  = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), p_donate_2016 >= 0.01, involved_online_ea, na.rm = TRUE)
          , "2016 Donate 1%? x involved book"    = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), p_donate_2016 >= 0.01, involved_book_blog, na.rm = TRUE)
          , "2016 Donate 1%? x would attend"     = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), p_donate_2016 >= 0.01, would_attend_local_group, na.rm = TRUE)
          , "2016 Donate 1%? x ea social"        = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), p_donate_2016 >= 0.01, ea_social, na.rm = TRUE)
          , "2016 Donate 10%?"                   = function(df) tab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), p_donate_2016 >= 0.1, percent = TRUE, byrow = FALSE, na.rm = TRUE)
          , "2016 Donate 10%? x member local"    = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), p_donate_2016 >= 0.1, member_local_group, na.rm = TRUE)
          , "2016 Donate 10%? x member EA Forum" = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), p_donate_2016 >= 0.1, member_ea_forum, na.rm = TRUE)
          , "2016 Donate 10%? x member EA FB"    = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), p_donate_2016 >= 0.1, member_ea_fb, na.rm = TRUE)
          , "2016 Donate 10%? x involved local"  = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), p_donate_2016 >= 0.1, involved_local_EA, na.rm = TRUE)
          , "2016 Donate 10%? x involved 80K"    = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), p_donate_2016 >= 0.1, involved_80K, na.rm = TRUE)
          , "2016 Donate 10%? x involved GW"     = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), p_donate_2016 >= 0.1, involved_givewell, na.rm = TRUE)
          , "2016 Donate 10%? x involved online" = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), p_donate_2016 >= 0.1, involved_online_ea, na.rm = TRUE)
          , "2016 Donate 10%? x involved book"   = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), p_donate_2016 >= 0.1, involved_book_blog, na.rm = TRUE)
          , "2016 Donate 10%? x would attend"    = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), p_donate_2016 >= 0.1, would_attend_local_group, na.rm = TRUE)
          , "2016 Donate 10%? x ea social"       = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), p_donate_2016 >= 0.1, ea_social, na.rm = TRUE)
          , "2016 Donate"                        = function(df) var_summary(filter(df, student == "No" & income_2016_individual_c >= 10000 & !(which_year_EA %in% c("2016", "2017")))$donate_2016_c, verbose = TRUE)
          , "2016 Donate x member local"         = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), donate_2016_c, member_local_group, na.rm = TRUE)
          , "2016 Donate x member EA Forum"      = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), donate_2016_c, member_ea_forum, na.rm = TRUE)
          , "2016 Donate x member EA FB"         = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), donate_2016_c, member_ea_fb, na.rm = TRUE)
          , "2016 Donate x involved local"       = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), donate_2016_c, involved_local_EA, na.rm = TRUE)
          , "2016 Donate x involved 80K"         = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), donate_2016_c, involved_80K, na.rm = TRUE)
          , "2016 Donate x involved GW"          = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), donate_2016_c, involved_givewell, na.rm = TRUE)
          , "2016 Donate x involved online"      = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), donate_2016_c, involved_online_ea, na.rm = TRUE)
          , "2016 Donate x involved book"        = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), donate_2016_c, involved_book_blog, na.rm = TRUE)
          , "2016 Donate x would attend"         = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), donate_2016_c, would_attend_local_group, na.rm = TRUE)
          , "2016 Donate x ea social"            = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), donate_2016_c, ea_social, na.rm = TRUE)
          , "2016 % Donate"                      = function(df) var_summary(filter(df, student == "No" & income_2016_individual_c >= 10000 & !(which_year_EA %in% c("2016", "2017")))$p_donate_2016, verbose = TRUE)
          , "2016 Income"                        = function(df) var_summary(filter(df, student == "No" & income_2016_individual_c >= 10000 & !(which_year_EA %in% c("2016", "2017")))$income_2016_individual_c, verbose = TRUE)
          , "2016 Income x member local"         = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), income_2016_individual_c, member_local_group, na.rm = TRUE)
          , "2016 Income x member EA Forum"      = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), income_2016_individual_c, member_ea_forum, na.rm = TRUE)
          , "2016 Income x member EA FB"         = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), income_2016_individual_c, member_ea_fb, na.rm = TRUE)
          , "2016 Income x involved local"       = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), income_2016_individual_c, involved_local_EA, na.rm = TRUE)
          , "2016 Income x involved 80K"         = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), income_2016_individual_c, involved_80K, na.rm = TRUE)
          , "2016 Income x involved GW"          = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), income_2016_individual_c, involved_givewell, na.rm = TRUE)
          , "2016 Income x involved online"      = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), income_2016_individual_c, involved_online_ea, na.rm = TRUE)
          , "2016 Income x involved book"        = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), income_2016_individual_c, involved_book_blog, na.rm = TRUE)
          , "2016 Income x would attend"         = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), income_2016_individual_c, would_attend_local_group, na.rm = TRUE)
          , "2016 Income x ea social"            = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), income_2016_individual_c, ea_social, na.rm = TRUE)
          , "2016 % Donate x member local"       = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), p_donate_2016, member_local_group, na.rm = TRUE)
          , "2016 % Donate x member EA Forum"    = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), p_donate_2016, member_ea_forum, na.rm = TRUE)
          , "2016 % Donate x member EA FB"       = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), p_donate_2016, member_ea_fb, na.rm = TRUE)
          , "2016 % Donate x involved local"     = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), p_donate_2016, involved_local_EA, na.rm = TRUE)
          , "2016 % Donate x involved 80K"       = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), p_donate_2016, involved_80K, na.rm = TRUE)
          , "2016 % Donate x involved GW"        = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), p_donate_2016, involved_givewell, na.rm = TRUE)
          , "2016 % Donate x involved online"    = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), p_donate_2016, involved_online_ea, na.rm = TRUE)
          , "2016 % Donate x involved book"      = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), p_donate_2016, involved_book_blog, na.rm = TRUE)
          , "2016 % Donate x would attend"       = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), p_donate_2016, would_attend_local_group, na.rm = TRUE)
          , "2016 % Donate x ea social"          = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), p_donate_2016, ea_social, na.rm = TRUE)
          , "2016 GWWC adherence (non-student, GWWC member)"                  = function(df) tab(df, filters(student == "No",  which_year_EA %not_in% c("2016", "2017"), member_gwwc == "Yes"), p_donate_2016 >= 0.1, percent = TRUE, byrow = FALSE, na.rm = TRUE)
          , "2016 GWWC adherence x local mem (non-student, GWWC member)"      = function(df) ctab(df, filters(student == "No",  which_year_EA %not_in% c("2016", "2017"), member_gwwc == "Yes"), p_donate_2016 >= 0.1, member_local_group, na.rm = TRUE)
          , "2016 GWWC adherence x local mem (non-student, GWWC member) tab"  = function(df) tab(df, filters(student == "No",  which_year_EA %not_in% c("2016", "2017"), member_gwwc == "Yes"), p_donate_2016 >= 0.1, member_local_group, na.rm = TRUE)
          , "2016 GWWC adherence (non-student non-GWWC member)"               = function(df) tab(df, filters(student == "No",  which_year_EA %not_in% c("2016", "2017"), member_gwwc == "No"), p_donate_2016 >= 0.1, percent = TRUE, byrow = FALSE, na.rm = TRUE)
          , "2016 GWWC adherence x local mem (non-student non-GWWC member)"   = function(df) ctab(df, filters(student == "No",  which_year_EA %not_in% c("2016", "2017"), member_gwwc == "No"), p_donate_2016 >= 0.1, member_local_group, na.rm = TRUE)
          , "2016 GWWC adherence (student GWWC member)"                       = function(df) tab(df, filters(student == "Yes", which_year_EA %not_in% c("2016", "2017"), member_gwwc == "Yes"), p_donate_2016 >= 0.01, percent = TRUE, byrow = FALSE, na.rm = TRUE)
          , "2016 GWWC adherence x local mem (student GWWC member)"           = function(df) ctab(df, filters(student == "Yes", which_year_EA %not_in% c("2016", "2017"), member_gwwc == "Yes"), p_donate_2016 >= 0.01, member_local_group, na.rm = TRUE)
          , "2015 Donate 1%?"                    = function(df) tab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), p_donate_2015 >= 0.01, percent = TRUE, byrow = FALSE, na.rm = TRUE)
          , "2015 Donate 1%? x member local"     = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), p_donate_2015 >= 0.01, member_local_group, na.rm = TRUE)
          , "2015 Donate 1%? x member EA Forum"  = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), p_donate_2015 >= 0.01, member_ea_forum, na.rm = TRUE)
          , "2015 Donate 1%? x member EA FB"     = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), p_donate_2015 >= 0.01, member_ea_fb, na.rm = TRUE)
          , "2015 Donate 1%? x involved local"   = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), p_donate_2015 >= 0.01, involved_local_EA, na.rm = TRUE)
          , "2015 Donate 1%? x involved 80K"     = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), p_donate_2015 >= 0.01, involved_80K, na.rm = TRUE)
          , "2015 Donate 1%? x involved GW"      = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), p_donate_2015 >= 0.01, involved_givewell, na.rm = TRUE)
          , "2015 Donate 1%? x involved online"  = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), p_donate_2015 >= 0.01, involved_online_ea, na.rm = TRUE)
          , "2015 Donate 1%? x involved book"    = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), p_donate_2015 >= 0.01, involved_book_blog, na.rm = TRUE)
          , "2015 Donate 1%? x would attend"     = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), p_donate_2015 >= 0.01, would_attend_local_group, na.rm = TRUE)
          , "2015 Donate 1%? x ea social"        = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), p_donate_2015 >= 0.01, ea_social, na.rm = TRUE)
          , "2015 Donate 10%?"                   = function(df) tab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), p_donate_2015 >= 0.1, percent = TRUE, byrow = FALSE, na.rm = TRUE)
          , "2015 Donate 10%? x member local"    = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), p_donate_2015 >= 0.1, member_local_group, na.rm = TRUE)
          , "2015 Donate 10%? x member EA Forum" = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), p_donate_2015 >= 0.1, member_ea_forum, na.rm = TRUE)
          , "2015 Donate 10%? x member EA FB"    = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), p_donate_2015 >= 0.1, member_ea_fb, na.rm = TRUE)
          , "2015 Donate 10%? x involved local"  = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), p_donate_2015 >= 0.1, involved_local_EA, na.rm = TRUE)
          , "2015 Donate 10%? x involved 80K"    = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), p_donate_2015 >= 0.1, involved_80K, na.rm = TRUE)
          , "2015 Donate 10%? x involved GW"     = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), p_donate_2015 >= 0.1, involved_givewell, na.rm = TRUE)
          , "2015 Donate 10%? x involved online" = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), p_donate_2015 >= 0.1, involved_online_ea, na.rm = TRUE)
          , "2015 Donate 10%? x involved book"   = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), p_donate_2015 >= 0.1, involved_book_blog, na.rm = TRUE)
          , "2015 Donate 10%? x would attend"    = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), p_donate_2015 >= 0.1, would_attend_local_group, na.rm = TRUE)
          , "2015 Donate 10%? x ea social"       = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), p_donate_2015 >= 0.1, ea_social, na.rm = TRUE)
          , "2015 Donate"                        = function(df) var_summary(filter(df, student == "No" & income_2015_individual_c >= 10000 & !(which_year_EA %in% c("2015", "2017")))$donate_2015_c, verbose = TRUE)
          , "2015 Donate x member local"         = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), donate_2015_c, member_local_group, na.rm = TRUE)
          , "2015 Donate x member EA Forum"      = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), donate_2015_c, member_ea_forum, na.rm = TRUE)
          , "2015 Donate x member EA FB"         = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), donate_2015_c, member_ea_fb, na.rm = TRUE)
          , "2015 Donate x involved local"       = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), donate_2015_c, involved_local_EA, na.rm = TRUE)
          , "2015 Donate x involved 80K"         = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), donate_2015_c, involved_80K, na.rm = TRUE)
          , "2015 Donate x involved GW"          = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), donate_2015_c, involved_givewell, na.rm = TRUE)
          , "2015 Donate x involved online"      = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), donate_2015_c, involved_online_ea, na.rm = TRUE)
          , "2015 Donate x involved book"        = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), donate_2015_c, involved_book_blog, na.rm = TRUE)
          , "2015 Donate x would attend"         = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), donate_2015_c, would_attend_local_group, na.rm = TRUE)
          , "2015 Donate x ea social"            = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), donate_2015_c, ea_social, na.rm = TRUE)
          , "2015 % Donate"                      = function(df) var_summary(filter(df, student == "No" & income_2015_individual_c >= 10000 & !(which_year_EA %in% c("2015", "2017")))$p_donate_2015, verbose = TRUE)
          , "2015 Income"                        = function(df) var_summary(filter(df, student == "No" & income_2015_individual_c >= 10000 & !(which_year_EA %in% c("2015", "2017")))$income_2015_individual_c, verbose = TRUE)
          , "2015 Income x member local"         = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), income_2015_individual_c, member_local_group, na.rm = TRUE)
          , "2015 Income x member EA Forum"      = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), income_2015_individual_c, member_ea_forum, na.rm = TRUE)
          , "2015 Income x member EA FB"         = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), income_2015_individual_c, member_ea_fb, na.rm = TRUE)
          , "2015 Income x involved local"       = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), income_2015_individual_c, involved_local_EA, na.rm = TRUE)
          , "2015 Income x involved 80K"         = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), income_2015_individual_c, involved_80K, na.rm = TRUE)
          , "2015 Income x involved GW"          = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), income_2015_individual_c, involved_givewell, na.rm = TRUE)
          , "2015 Income x involved online"      = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), income_2015_individual_c, involved_online_ea, na.rm = TRUE)
          , "2015 Income x involved book"        = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), income_2015_individual_c, involved_book_blog, na.rm = TRUE)
          , "2015 Income x would attend"         = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), income_2015_individual_c, would_attend_local_group, na.rm = TRUE)
          , "2015 Income x ea social"            = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), income_2015_individual_c, ea_social, na.rm = TRUE)
          , "2015 % Donate x member local"       = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), p_donate_2015, member_local_group, na.rm = TRUE)
          , "2015 % Donate x member EA Forum"    = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), p_donate_2015, member_ea_forum, na.rm = TRUE)
          , "2015 % Donate x member EA FB"       = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), p_donate_2015, member_ea_fb, na.rm = TRUE)
          , "2015 % Donate x involved local"     = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), p_donate_2015, involved_local_EA, na.rm = TRUE)
          , "2015 % Donate x involved 80K"       = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), p_donate_2015, involved_80K, na.rm = TRUE)
          , "2015 % Donate x involved GW"        = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), p_donate_2015, involved_givewell, na.rm = TRUE)
          , "2015 % Donate x involved online"    = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), p_donate_2015, involved_online_ea, na.rm = TRUE)
          , "2015 % Donate x involved book"      = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), p_donate_2015, involved_book_blog, na.rm = TRUE)
          , "2015 % Donate x would attend"       = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), p_donate_2015, would_attend_local_group, na.rm = TRUE)
          , "2015 % Donate x ea social"          = function(df) ctab(df, filters(student == "No", income_2015_individual_c >= 10000, which_year_EA %not_in% c("2015", "2017")), p_donate_2015, ea_social, na.rm = TRUE)
          , "2015 GWWC adherence (non-student, GWWC member)"                 = function(df) tab(df, filters(student == "No",  which_year_EA %not_in% c("2015", "2016", "2017"), member_gwwc == "Yes"), p_donate_2015 >= 0.1, percent = TRUE, byrow = FALSE, na.rm = TRUE)
          , "2015 GWWC adherence x local mem (non-student, GWWC member)"     = function(df) ctab(df, filters(student == "No",  which_year_EA %not_in% c("2015", "2016", "2017"), member_gwwc == "Yes"), p_donate_2015 >= 0.1, member_local_group, na.rm = TRUE)
          , "2015 GWWC adherence x local mem (non-student, GWWC member) tab" = function(df) tab(df, filters(student == "No",  which_year_EA %not_in% c("2015", "2016", "2017"), member_gwwc == "Yes"), p_donate_2015 >= 0.1, member_local_group, na.rm = TRUE)
          , "2015 GWWC adherence (non-student non-GWWC member)"              = function(df) tab(df, filters(student == "No",  which_year_EA %not_in% c("2015", "2016", "2017"), member_gwwc == "No"), p_donate_2015 >= 0.1, percent = TRUE, byrow = FALSE, na.rm = TRUE)
          , "2015 GWWC adherence x local mem (non-student non-GWWC member)"  = function(df) ctab(df, filters(student == "No",  which_year_EA %not_in% c("2015", "2016", "2017"), member_gwwc == "No"), p_donate_2015 >= 0.1, member_local_group, na.rm = TRUE)
          , "2015 GWWC adherence (student GWWC member)"                      = function(df) tab(df, filters(student == "Yes", which_year_EA %not_in% c("2015", "2016", "2017"), member_gwwc == "Yes"), p_donate_2015 >= 0.01, percent = TRUE, byrow = FALSE, na.rm = TRUE)
          , "2015 GWWC adherence x local mem (student GWWC member)"          = function(df) ctab(df, filters(student == "Yes", which_year_EA %not_in% c("2015", "2016", "2017"), member_gwwc == "Yes"), p_donate_2015 >= 0.01, member_local_group, na.rm = TRUE)
          , "2015 x 2016 GWWC adherence (non-student, GWWC member)"          = function(df) ctab(df, filters(student == "No",  which_year_EA %not_in% c("2015", "2016", "2017"), member_gwwc == "Yes"), p_donate_2015 >= 0.1, p_donate_2016 >= 0.1, na.rm = TRUE)
          , "2016 x 2015 GWWC adherence (non-student, GWWC member)"          = function(df) ctab(df, filters(student == "No",  which_year_EA %not_in% c("2015", "2016", "2017"), member_gwwc == "Yes"), p_donate_2016 >= 0.1, p_donate_2015 >= 0.1, na.rm = TRUE)
          , "Cities of local groups"             		 = function(df) tab(df, filter(member_local_group == "Yes"), city, top = 10)
					, "Top 25 local groups by num people"  		 = function(df) tab(df, group1, top = 25)
					, "People in LEAN groups"              		 = function(df) tab(df, is_lean, percent = TRUE, byrow = FALSE, na.rm = TRUE)
					, "Top 25 LEAN groups by num people"   		 = function(df) tab(df, filter(is_lean == TRUE), group1, top = 25)
					, "Top 25 non-LEAN groups by num people"   = function(df) tab(df, filter(is_lean == FALSE), group1, top = 25)
					, "Welcoming x LEAN group"                 = function(df) ctab(df, ea_welcoming, is_lean, na.rm = TRUE)
					, "EA NPS x LEAN group"										 = function(df) ctab(df, ea_nps, is_lean, na.rm = TRUE)
          , "first local x LEAN group"               = function(df) tab(df, first_local, is_lean, percent = TRUE, byrow = FALSE, na.rm = TRUE)
          , "invovled local x LEAN group"            = function(df) tab(df, involved_local_EA, is_lean, percent = TRUE, byrow = FALSE, na.rm = TRUE)
					, "ea_donate x LEAN group"                 = function(df) ctab(df, ea_donate, is_lean, na.rm = TRUE)
					, "2016 % Donate x LEAN group"             = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), p_donate_2016, is_lean, na.rm = TRUE)
					, "2016 Donate x LEAN group"               = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), donate_2016_c, is_lean, na.rm = TRUE)
					, "GWWC Membership x LEAN group"           = function(df) tab(df, member_gwwc, is_lean, percent = TRUE, byrow = FALSE)
					, "GWWC Membership x LEAN group II"        = function(df) tab(df, member_gwwc, is_lean, percent = TRUE, byrow = FALSE, na.rm = TRUE)
					, "GWWC Membership x LEAN group III"       = function(df) tab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), member_gwwc, is_lean, percent = TRUE, byrow = FALSE)
					, "GWWC Membership x LEAN group IV"        = function(df) tab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), member_gwwc, is_lean, percent = TRUE, byrow = FALSE, na.rm = TRUE)
					, "GWWC Membership x LEAN group V"         = function(df) ctab(df, filters(student == "No", income_2016_individual_c >= 10000, which_year_EA %not_in% c("2016", "2017")), member_gwwc, is_lean, na.rm = TRUE)
					, "GWWC adherence x LEAN group"            = function(df) ctab(df, filter(member_gwwc == "Yes"), p_donate_2016 >= 0.1, is_lean, na.rm = TRUE)
					, "ea_career x LEAN group"                 = function(df) ctab(df, ea_career, is_lean, na.rm = TRUE)
					, "ea_volunteer x LEAN group"              = function(df) ctab(df, ea_volunteer, is_lean, na.rm = TRUE)
					, "vol hrs x LEAN group"                   = function(df) ctab(df, ea_volunteer_hours, is_lean, na.rm = TRUE)
					, "paid hrs x LEAN group"                  = function(df) ctab(df, ea_paid_hours, is_lean, na.rm = TRUE)
       ))) })

