Ramd::define("referrers", "simple_referrers", function(referrer_list, simple_referrer_list) {
  list(
    import = list(file = "data/imsurvey2017-anonymized-currencied.csv"),

    data   = list(
      "Drop insincere"   = function(df) { dplyr::filter(df, grepl("Yes", sincere)) }
      , "Drop non-EA"    = function(df) { dplyr::filter(df, grepl("Yes", is_ea)) }
      , "Create age"     = function(df) { df$age <- 2017 - as.numeric(df$birth_year); df }
      , "Make % inc donate [2015]" = function(df) {
          p <- df$donate_2015_c / df$income_2015_individual_c
          p[is.infinite(p)] <- NA
          df$p_donate_2015 <- p
          df
      }
      , "Make % inc donate [2016]" = function(df) {
          p <- df$donate_2016_c / df$income_2016_individual_c
          p[is.infinite(p)] <- NA
          df$p_donate_2016 <- p
          df
      }
      , "Make referrer_url" = function(df) { surveytools2::swap_by_value(df, "referrer_url", referrer_list, grep = TRUE) }
      , "Make simple_referrer" = function(df) { df$referrer2 <- surveytools2::swap_by_value(df, "referrer_url", referrer_list, grep = TRUE)$referrer_url; df }
    )

    , analyze = list(
      list(write = "2017-survey-analysis-tables.txt"),
      list(
        "num respondents"                 = function(df) num_respondents(df)
        , "first heard about EA"          = function(df) tab(df, first_heard_EA)
        , "EA year"                       = function(df) tab(df, which_year_EA)
        , "how heard x year"              = function(df) ctab(df, first_heard_EA, which_year_EA)
        , "how heard x year (freq)"       = function(df) tab(df, first_heard_EA, which_year_EA)
        , "involved_TLYCS"                = function(df) tab(df, involved_TLYCS)
        , "involved_local_EA"             = function(df) tab(df, involved_local_EA)
        , "involved_lesswrong"            = function(df) tab(df, involved_lesswrong)
        , "involved_givewell"             = function(df) tab(df, involved_givewell)
        , "involved_online_ea"            = function(df) tab(df, involved_online_ea)
        , "involved_personal_contact"     = function(df) tab(df, involved_personal_contact)
        , "involved_80K"                  = function(df) tab(df, involved_80K)
        , "involved_GWWC"                 = function(df) tab(df, involved_GWWC)
        , "involved EA Global"            = function(df) tab(df, involved_ea_global)
        , "involved Book or Blog"         = function(df) tab(df, involved_book_blog)
        , "involved Swiss"                = function(df) tab(df, involved_swiss)
        , "member_ea_fb"                  = function(df) tab(df, member_ea_fb)
        , "member_ea_forum"               = function(df) tab(df, member_ea_forum)
        , "member_gwwc"                   = function(df) tab(df, member_gwwc)
        , "member_lw"                     = function(df) tab(df, member_lw)
        , "member_tlycs"                  = function(df) tab(df, member_tlycs)
        , "member_local_group"            = function(df) tab(df, member_local_group)
        , "ea_donate"                     = function(df) tab(df, ea_donate)
        , "ea_volunteer"                  = function(df) tab(df, ea_volunteer)
        , "ea_career"                     = function(df) tab(df, ea_career)
        , "ea_volunteer_hours"            = function(df) tab(df, ea_volunteer_hours)
        , "ea_paid_hours"                 = function(df) tab(df, ea_paid_hours)
        , "would_like_more_involvement"   = function(df) tab(df, would_like_more_involvement)
        , "ea_nps"                        = function(df) tab(df, ea_nps)
        , "gender"                        = function(df) tab(df, gender)
        , "race_white"                    = function(df) tab(df, race_white)
        , "race_black"                    = function(df) tab(df, race_black)
        , "race_hispanic"                 = function(df) tab(df, race_hispanic)
        , "race_asian"                    = function(df) tab(df, race_asian)
        , "age"                           = function(df) tab(df, age)
        , "religion"                      = function(df) tab(df, religion)
        , "student"                       = function(df) tab(df, student)
        , "employment_status"             = function(df) tab(df, employment_status)
        , "field"                         = function(df) tab(df, field)
        , "country"                       = function(df) tab(df, country)
        , "city"                          = function(df) tab(df, city)
        , "cause_import_animal_welfare"   = function(df) tab(df, cause_import_animal_welfare)
        , "cause_import_cause_prioritization"  = function(df) tab(df, cause_import_cause_prioritization)
        , "cause_import_environmentalism"      = function(df) tab(df, cause_import_environmentalism)
        , "cause_import_ai"                    = function(df) tab(df, cause_import_ai)
        , "cause_import_non_ai_far_future"     = function(df) tab(df, cause_import_non_ai_far_future)
        , "cause_import_poverty"          = function(df) tab(df, cause_import_poverty)
        , "cause_import_rationality"      = function(df) tab(df, cause_import_rationality)
        , "cause_import_politics"         = function(df) tab(df, cause_import_politics)
        , "cause_import_meta"             = function(df) tab(df, cause_import_meta)
        , "first heard through local grp" = function(df) tab(df, first_heard_EA == "Local EA group")
        , "first heard local x GWWC mem"  = function(df) ctab(df, member_gwwc, first_heard_EA == "Local EA group")
        , "total donated (2015)"          = function(df) sum(df$donate_2015_c, na.rm = TRUE)
        , "total donated (2016)"          = function(df) sum(df$donate_2016_c, na.rm = TRUE)
        , "first heard local x donate"    = function(df) ctab(df, donate_2016_c, first_heard_EA == "Local EA group")
        , "would attend"                  = function(df) tab(df, would_attend_local_group)
        , "involved_local_EA x GWWC invo" = function(df) ctab(df, involved_local_EA, involved_GWWC)
        , "involved_local_EA x GWWC mem"  = function(df) ctab(df, involved_local_EA, member_gwwc)
        , "involved_GWWC x GWWC mem"      = function(df) ctab(df, involved_GWWC, member_gwwc)
        , "involved_local_EA x donate"    = function(df) ctab(df, donate_2016_c, involved_local_EA)
        , "member_local x GWWC"           = function(df) ctab(df, member_local_group, member_gwwc)
        , "involved_local_EA x local mem" = function(df) ctab(df, involved_local_EA, member_local_group)
        , "member_local x year"           = function(df) ctab(df, member_local_group, which_year_EA)
        , "member_local x donate"         = function(df) ctab(df, donate_2016_c, member_local_group)
        , "GWWC x donate"                 = function(df) ctab(df, donate_2016_c, member_gwwc)
        , "member_local x donate %"       = function(df) ctab(df, p_donate_2016, member_local_group)
        , "GWWC x donate %"               = function(df) ctab(df, p_donate_2016, member_gwwc)
        , "GWWC x donate % (inc > $10k)"  = function(df) ctab(dplyr::filter(df, income_2016_individual_c > 10000), p_donate_2016, member_gwwc)
        , "GWWC x donate 10% or more (inc > $10K)"  = function(df) ctab(dplyr::filter(df, income_2016_individual_c > 10000), p_donate_2016 > 0.0999999, member_gwwc, na.rm = TRUE) #avoid float-point comparison problem
        , "member_local x student"        = function(df) ctab(df, member_local_group, student)
        , "member_local x welcoming"      = function(df) ctab(df, member_local_group, ea_welcoming)
        , "member_gwwc x welcoming"       = function(df) ctab(df, member_gwwc, ea_welcoming)
        , "member_local x fundraiser"     = function(df) ctab(df, member_local_group, action_fundraiser)
        , "member_gwwc x fundraiser"      = function(df) ctab(df, member_gwwc, action_fundraiser)
        , "member_local x legacy"         = function(df) ctab(df, member_local_group, action_legacy)
        , "member_gwwc x legacy"          = function(df) ctab(df, member_gwwc, action_legacy)
        , "member_local x telling_friends"     = function(df) ctab(df, member_local_group, action_telling_friends)
        , "member_gwwc x telling_friends"      = function(df) ctab(df, member_gwwc, action_telling_friends)
        , "member_local x ea_newsletter"       = function(df) ctab(df, member_local_group, action_ea_newsletter)
        , "member_gwwc x ea_newsletter"        = function(df) ctab(df, member_gwwc, action_ea_newsletter)
        , "RC Donations 2015 (Total)"          = function(df) tab(df, donate_RC_2015_c)
        , "RC Donations 2016 (Total)"          = function(df) tab(df, donate_RC_2016_c)
        , "Did donate to RC 2015?"             = function(df) tab(df, donate_RC_2015_c > 0)
        , "Did donate to RC 2016?"             = function(df) tab(df, donate_RC_2016_c > 0)
        , "80K Donations 2015 (Total)"         = function(df) tab(df, donate_80K_2015_c)
        , "80K Donations 2016 (Total)"         = function(df) tab(df, donate_80K_2016_c)
        , "Did donate to 80K 2015?"            = function(df) tab(df, donate_80K_2015_c > 0)
        , "Did donate to 80K 2016?"            = function(df) tab(df, donate_80K_2016_c > 0)
        , "AMF Donations 2015 (Total)"         = function(df) tab(df, donate_amf_2015_c)
        , "AMF Donations 2016 (Total)"         = function(df) tab(df, donate_amf_2016_c)
        , "Did donate to AMF 2015?"            = function(df) tab(df, donate_amf_2015_c > 0)
        , "Did donate to AMF 2016?"            = function(df) tab(df, donate_amf_2016_c > 0)
        , "ACE Donations 2015 (Total)"         = function(df) tab(df, donate_ace_2015_c)
        , "ACE Donations 2016 (Total)"         = function(df) tab(df, donate_ace_2016_c)
        , "Did donate to ACE 2015?"            = function(df) tab(df, donate_ace_2015_c > 0)
        , "Did donate to ACE 2016?"            = function(df) tab(df, donate_ace_2016_c > 0)
        , "CFAR Donations 2015 (Total)"         = function(df) tab(df, donate_cfar_2015_c)
        , "CFAR Donations 2016 (Total)"         = function(df) tab(df, donate_cfar_2016_c)
        , "Did donate to CFAR 2015?"            = function(df) tab(df, donate_cfar_2015_c > 0)
        , "Did donate to CFAR 2016?"            = function(df) tab(df, donate_cfar_2016_c > 0)
        , "CEA Donations 2015 (Total)"         = function(df) tab(df, donate_cea_2015_c)
        , "CEA Donations 2016 (Total)"         = function(df) tab(df, donate_cea_2016_c)
        , "Did donate to CEA 2015?"            = function(df) tab(df, donate_cea_2015_c > 0)
        , "Did donate to CEA 2016?"            = function(df) tab(df, donate_cea_2016_c > 0)
        , "CS Donations 2015 (Total)"         = function(df) tab(df, donate_cs_2015_c)
        , "CS Donations 2016 (Total)"         = function(df) tab(df, donate_cs_2016_c)
        , "Did donate to CS 2015?"            = function(df) tab(df, donate_cs_2015_c > 0)
        , "Did donate to CS 2016?"            = function(df) tab(df, donate_cs_2016_c > 0)
        , "DTW Donations 2015 (Total)"         = function(df) tab(df, donate_dtw_2015_c)
        , "DTW Donations 2016 (Total)"         = function(df) tab(df, donate_dtw_2016_c)
        , "Did donate to DTW 2015?"            = function(df) tab(df, donate_dtw_2015_c > 0)
        , "Did donate to DTW 2016?"            = function(df) tab(df, donate_dtw_2016_c > 0)
        , "EF Donations 2015 (Total)"         = function(df) tab(df, donate_ef_2015_c)
        , "EF Donations 2016 (Total)"         = function(df) tab(df, donate_ef_2016_c)
        , "Did donate to EF 2015?"            = function(df) tab(df, donate_ef_2015_c > 0)
        , "Did donate to EF 2016?"            = function(df) tab(df, donate_ef_2016_c > 0)
        , "END Fund Donations 2015 (Total)"   = function(df) tab(df, donate_end_2015_c)
        , "END Fund Donations 2016 (Total)"   = function(df) tab(df, donate_end_2016_c)
        , "Did donate to END Fund 2015?"      = function(df) tab(df, donate_end_2015_c > 0)
        , "Did donate to END Fund 2016?"      = function(df) tab(df, donate_end_2016_c > 0)
        , "Faunalytics Donations 2015 (Total)" = function(df) tab(df, donate_faunalytics_2015_c)
        , "Faunalytics Donations 2016 (Total)" = function(df) tab(df, donate_faunalytics_2016_c)
        , "Did donate to Faunalytics 2015?"   = function(df) tab(df, donate_faunalytics_2015_c > 0)
        , "Did donate to Faunalytics 2016?"   = function(df) tab(df, donate_faunalytics_2016_c > 0)
        , "FRI Donations 2015 (Total)"        = function(df) tab(df, donate_fri_2015_c)
        , "FRI Donations 2016 (Total)"        = function(df) tab(df, donate_fri_2016_c)
        , "Did donate to FRI 2015?"           = function(df) tab(df, donate_fri_2015_c > 0)
        , "Did donate to FRI 2016?"           = function(df) tab(df, donate_fri_2016_c > 0)
        , "FHI Donations 2015 (Total)"        = function(df) tab(df, donate_fhi_2015_c)
        , "FHI Donations 2016 (Total)"        = function(df) tab(df, donate_fhi_2016_c)
        , "Did donate to FHI 2015?"           = function(df) tab(df, donate_fhi_2015_c > 0)
        , "Did donate to FHI 2016?"           = function(df) tab(df, donate_fhi_2016_c > 0)
        , "GD Donations 2015 (Total)"         = function(df) tab(df, donate_gd_2015_c)
        , "GD Donations 2016 (Total)"         = function(df) tab(df, donate_gd_2016_c)
        , "Did donate to GD 2015?"            = function(df) tab(df, donate_gd_2015_c > 0)
        , "Did donate to GD 2016?"            = function(df) tab(df, donate_gd_2016_c > 0)
        , "GW Donations 2015 (Total)"         = function(df) tab(df, donate_gw_2015_c)
        , "GW Donations 2016 (Total)"         = function(df) tab(df, donate_gw_2016_c)
        , "Did donate to GW 2015?"            = function(df) tab(df, donate_gw_2015_c > 0)
        , "Did donate to GW 2016?"            = function(df) tab(df, donate_gw_2016_c > 0)
        , "GF Donations 2015 (Total)"         = function(df) tab(df, donate_gf_2015_c)
        , "GF Donations 2016 (Total)"         = function(df) tab(df, donate_gf_2016_c)
        , "Did donate to GF 2015?"            = function(df) tab(df, donate_gf_2015_c > 0)
        , "Did donate to GF 2016?"            = function(df) tab(df, donate_gf_2016_c > 0)
        , "MIRI Donations 2015 (Total)"       = function(df) tab(df, donate_miri_2015_c)
        , "MIRI Donations 2016 (Total)"       = function(df) tab(df, donate_miri_2016_c)
        , "Did donate to MIRI 2015?"          = function(df) tab(df, donate_miri_2015_c > 0)
        , "Did donate to MIRI 2016?"          = function(df) tab(df, donate_miri_2016_c > 0)
        , "MC Donations 2015 (Total)"         = function(df) tab(df, donate_mc_2015_c)
        , "MC Donations 2016 (Total)"         = function(df) tab(df, donate_mc_2016_c)
        , "Did donate to MC 2015?"            = function(df) tab(df, donate_mc_2015_c > 0)
        , "Did donate to MC 2016?"            = function(df) tab(df, donate_mc_2016_c > 0)
        , "MFA Donations 2015 (Total)"        = function(df) tab(df, donate_mfa_2015_c)
        , "MFA Donations 2016 (Total)"        = function(df) tab(df, donate_mfa_2016_c)
        , "Did donate to MFA 2015?"           = function(df) tab(df, donate_mfa_2015_c > 0)
        , "Did donate to MFA 2016?"           = function(df) tab(df, donate_mfa_2016_c > 0)
        , "SCI Donations 2015 (Total)"        = function(df) tab(df, donate_sci_2015_c)
        , "SCI Donations 2016 (Total)"        = function(df) tab(df, donate_sci_2016_c)
        , "Did donate to SCI 2015?"           = function(df) tab(df, donate_sci_2015_c > 0)
        , "Did donate to SCI 2016?"           = function(df) tab(df, donate_sci_2016_c > 0)
        , "Sightsavers Donations 2015 (Total)" = function(df) tab(df, donate_sightsavers_2015_c)
        , "Sightsavers Donations 2016 (Total)" = function(df) tab(df, donate_sightsavers_2016_c)
        , "Did donate to Sightsavers 2015?"   = function(df) tab(df, donate_sightsavers_2015_c > 0)
        , "Did donate to Sightsavers 2016?"   = function(df) tab(df, donate_sightsavers_2016_c > 0)
        , "SP Donations 2015 (Total)"         = function(df) tab(df, donate_sp_2015_c)
        , "SP Donations 2016 (Total)"         = function(df) tab(df, donate_sp_2016_c)
        , "Did donate to SP 2015?"            = function(df) tab(df, donate_sp_2015_c > 0)
        , "Did donate to SP 2016?"            = function(df) tab(df, donate_sp_2016_c > 0)
        , "THL Donations 2015 (Total)"         = function(df) tab(df, donate_thl_2015_c)
        , "THL Donations 2016 (Total)"         = function(df) tab(df, donate_thl_2016_c)
        , "Did donate to THL 2015?"            = function(df) tab(df, donate_thl_2015_c > 0)
        , "Did donate to THL 2016?"            = function(df) tab(df, donate_thl_2016_c > 0)
        , "TLYCS Donations 2015 (Total)"       = function(df) tab(df, donate_tlycs_2015_c)
        , "TLYCS Donations 2016 (Total)"       = function(df) tab(df, donate_tlycs_2016_c)
        , "Did donate to TLYCS 2015?"          = function(df) tab(df, donate_tlycs_2015_c > 0)
        , "Did donate to TLYCS 2016?"          = function(df) tab(df, donate_tlycs_2016_c > 0)
        , "MIRI donations by year"        = function(df) ctab(df %>% dplyr::filter(donate_2016_c > 0), donate_miri_2016_c, which_year_EA, na.rm = TRUE)
        , "AMF donations by year"         = function(df) ctab(df %>% dplyr::filter(donate_2016_c > 0), donate_amf_2016_c, which_year_EA, na.rm = TRUE)
        , "AMF donations by first heard"  = function(df) ctab(df %>% dplyr::filter(donate_2016_c > 0), donate_amf_2016_c, first_heard_EA, na.rm = TRUE)
        , "AMF donations by  url"  = function(df) ctab(df %>% dplyr::filter(donate_2016_c > 0), donate_amf_2016_c, referrer_url, na.rm = TRUE)    
        , "MIRI donations by first heard"      = function(df) ctab(df %>% dplyr::filter(donate_2016_c > 0), donate_miri_2016_c, first_heard_EA, na.rm = TRUE) 
        , "MIRI donations by first heard 2"    = function(df) tab(df %>% dplyr::filter(donate_2016_c > 0), donate_miri_2016_c, first_heard_EA, na.rm = TRUE, freq = TRUE, percent = TRUE)    
        , "MIRI donations by first heard"      = function(df) ctab(df %>% dplyr::filter(donate_2016_c > 0), donate_miri_2016_c, first_heard_EA, na.rm = TRUE)
        , "summarize donations"           = function(df) summary(df[!is.na(df$donate_2016_c),]$donate_2016_c)    
        , "number of >0 donations"        = function(df) sum(df$donate_2016_c > 0, na.rm = TRUE)
        , "donation quantile 1"           = function(df) quantile(df$donate_2016_c, probs = seq(0.1, 1, len = 10), na.rm = TRUE)
        , "donation quantile 2"           = function(df) quantile(df$donate_2016_c, probs = seq(0.91, 1, len = 10), na.rm = TRUE)
        , "donating 10% or over x GWWC"      = function(df) ctab(df, p_donate_2016 > 0.0999999, member_gwwc)    
        , "summarize donations - fb sample"= function(df) var_summary(dplyr::filter(df, referrer_url=="No Referrer", !is.na(donate_2016_c))$donate_2016_c)    
        , "summarize donations - student" 	      = function(df) var_summary(dplyr::filter(df, student == "Yes" & !is.na(student) & !is.na(donate_2016_c))$donate_2016_c)
        , "summarize donations - non-student" 	      = function(df) var_summary(dplyr::filter(df, student == "No" & student != "NA" & donate_2016_c != "NA")$donate_2016_c)
        , "summarize donations - got involved pre-2013" 	      = function(df) var_summary(dplyr::filter(df, !((which_year_EA == "2016") | (which_year_EA == "2015")) & donate_2016_c != "NA" & !is.na(which_year_EA))$donate_2016_c)
        , "summarize % donations"         = function(df) var_summary(df$p_donate_2016)
        , "summarize % donations (inc > $10k)"         = function(df) var_summary(dplyr::filter(df, income_2016_individual_c > 10000 & p_donate_2016 != "NA")$p_donate_2016)    
        , "# people donating 10% or over"    = function(df) sum(df[df$income_2016_individual_c > 10000, "p_donate_2016"] > 0.09999999, na.rm = TRUE) #avoid floating point comparison error
        , "donating over 10% x GWWC"      = function(df) ctab(df, p_donate_2016 > 0.1, member_gwwc)        
        , "% donation quantile 1"         = function(df) quantile(df[df$income_2016_individual_c > 10000, "p_donate_2016"], probs = seq(0.1, 1, len = 10), na.rm = TRUE)
        , "% donation quantile 2"         = function(df) quantile(df[df$income_2016_individual_c > 10000, "p_donate_2016"], probs = seq(0.91, 1, len = 10), na.rm = TRUE)        
        , "diet"                          = function(df) tab(df, veg)
        , "diet x cause_import_animal_welfare" = function(df) ctab(df, veg, cause_import_animal_welfare, na.rm = TRUE)
        , "opportunity or obligation"     = function(df) tab(df, ea_opportunity_or_obligation)
        , "act now or later"              = function(df) tab(df, act_now_or_later)
        , "act now or later x age"        = function(df) tab(df, age, act_now_or_later)
        , "moral philosophy"              = function(df) tab(df, moral_philosophy)
        , "confidence in personal EA"     = function(df) tab(df, confident_future_ea_personal)
        , "confidence in EA movement"     = function(df) tab(df, confident_future_ea_movement)
        , "confidence x confidence"       = function(df) ctab(df, confident_future_ea_personal, confident_future_ea_movement, na.rm = TRUE)
        , "confidence x confidence (raw)" = function(df) tab(df, confident_future_ea_personal, confident_future_ea_movement)
        , "EA topic"                      = function(df) tab(df, topic_ea)
        , "EA Welcoming"                  = function(df) tab(df, ea_welcoming)
        , "EA Welcoming x gender"         = function(df) ctab(df, gender, ea_welcoming, na.rm = TRUE)
        , "EA Welcoming x age"            = function(df) ctab(df, age, ea_welcoming, na.rm = TRUE)
        , "EA Welcoming x religion"       = function(df) ctab(df, religion == "Atheist, agnostic or non-religious", ea_welcoming, na.rm = TRUE)
        , "EA Welcoming x ethics"         = function(df) ctab(df, moral_philosophy == "Consequentialism (utilitarian)", ea_welcoming, na.rm = TRUE)
        , "Insecurity about EA"           = function(df) tab(df, insecurity)
        , "opportunity-oblication x inse" = function(df) ctab(df, insecurity, ea_opportunity_or_obligation, na.rm = TRUE)
        , "referrer URL"                  = function(df) tab(df, referrer_url)
        , "referrer self-report"          = function(df) tab(df, referrer_self_report)
        , "referrer x referrer"           = function(df) ctab(df, referrer_url, referrer_self_report)
        , "referrer URL x gender"         = function(df) ctab(df, gender, referrer_url)
        , "referrer URL x age"            = function(df) ctab(df, age, referrer_url)
        , "referrer URL x ethics"         = function(df) ctab(df, moral_philosophy, referrer_url)
        , "referrer self-report x gender" = function(df) ctab(df, gender, referrer_self_report)
        , "referrer self-report x age"    = function(df) ctab(df, age, referrer_self_report)
        , "referrer self-report x ethics" = function(df) ctab(df, moral_philosophy, referrer_self_report)
        , "referrer2"                     = function(df) tab(df, referrer2)
        , "referrer2 x age"               = function(df) ctab(df, age, referrer2, na.rm = TRUE)
        , "referrer2 x donation"          = function(df) ctab(dplyr::filter(df, student == "No"), donate_2016_c, referrer2, na.rm = TRUE)
        , "referrer2 x income"            = function(df) ctab(dplyr::filter(df, student == "No"), income_2016_individual_c, referrer2, na.rm = TRUE)
        , "referrer2 x % income donate"   = function(df) ctab(dplyr::filter(df, student == "No" & income_2016_individual_c > 9999), p_donate_2016, referrer2, na.rm = TRUE)    
        , "referrer2 x poverty"           = function(df) ctab(df, cause_import_poverty == "This cause should be the top priority", referrer2, na.rm = TRUE)
        , "referrer2 x student"           = function(df) ctab(df, student, referrer2, na.rm = TRUE)
        , "referrer2 x veg"               = function(df) ctab(df, veg == "Vegetarian" | veg == "Vegan", referrer2, na.rm = TRUE)
        , "referrer2 x year got involved" = function(df) ctab(df, which_year_EA, referrer2, na.rm = TRUE)
        # , "solid EA x city"               = function(df) ctab(df, solid_ea, city)
      )
    )
  )
})
