list(
  import = list(file = "data/imsurvey-longitudinal.csv"),
  analyze = list(
    "involved_TLYCS"                  = function(df) ctab(df, involved_TLYCS.x, involved_TLYCS.y)
    , "involved_local_EA"             = function(df) ctab(df, involved_local_EA.x, involved_local_EA.y)
    , "involved_lesswrong"            = function(df) ctab(df, involved_lesswrong.x, involved_lesswrong.y)
    , "involved_givewell"             = function(df) ctab(df, involved_givewell.x, involved_givewell.y)
    , "involved_online_ea"            = function(df) ctab(df, involved_online_ea.x, involved_online_ea.y)
    , "involved_80K"                  = function(df) ctab(df, involved_80K.x, involved_80K.y)
    , "cause_import_cause_prioritization"  = function(df) ctab(df, cause_import_cause_prioritization.x, cause_import_cause_prioritization.y)
    , "cause_import_environmentalism"      = function(df) ctab(df, cause_import_environmentalism.x, cause_import_environmentalism.y)
    , "cause_import_ai"                    = function(df) ctab(df, cause_import_ai.x, cause_import_ai.y)
    , "cause_import_non_ai_far_future"     = function(df) ctab(df, cause_import_non_ai_far_future.x, cause_import_non_ai_far_future.y)
    , "cause_import_poverty"          = function(df) ctab(df, cause_import_poverty.x, cause_import_poverty.y)
    , "cause_import_rationality"      = function(df) ctab(df, cause_import_rationality.x, cause_import_rationality.y)
    , "cause_import_politics"         = function(df) ctab(df, cause_import_politics.x, cause_import_politics.y)
    , "cause_import_meta"             = function(df) ctab(df, cause_import_meta.x, cause_import_meta.y)
    , "donate_80K"                    = function(df) ctab(df, donate_80K.x, donate_80K.y)
    , "donate_amf"                    = function(df) ctab(df, donate_amf.x, donate_amf.y)
    , "donate_ace"                    = function(df) ctab(df, donate_ace.x, donate_ace.y)
    , "donate_cea"                    = function(df) ctab(df, donate_cea.x, donate_cea.y)
    , "donate_cfar"                   = function(df) ctab(df, donate_cfar.x, donate_cfar.y)
    , "donate_dtw"                    = function(df) ctab(df, donate_dtw.x, donate_dtw.y)
    , "donate_gd"                     = function(df) ctab(df, donate_gd.x, donate_gd.y)
    , "donate_gw"                     = function(df) ctab(df, donate_gw.x, donate_gw.y)
    , "donate_gwwc"                   = function(df) ctab(df, donate_gwwc.x, donate_gwwc.y)
    , "donate_thl"                    = function(df) ctab(df, donate_thl.x, donate_thl.y)
    , "donate_leverage"               = function(df) ctab(df, donate_leverage.x, donate_leverage.y)
    , "donate_miri"                   = function(df) ctab(df, donate_miri.x, donate_miri.y)
    , "donate_phc"                    = function(df) ctab(df, donate_phc.x, donate_phc.y)
    , "donate_sci"                    = function(df) ctab(df, donate_sci.x, donate_sci.y)
    , "donate_vo"                     = function(df) ctab(df, donate_vo.x, donate_vo.y)
    , "donation delta"                = function(df) var_summary(df$donate_2014_c - df$donate_2013_c)
    , "veg"                           = function(df) ctab(df, veg.y, veg.x, na.rm = TRUE)
  )
)
